export * from './ClusterEntity';
export * from './CollateralEntity';
export * from './LoanEntity';
export * from './OwnerEntity';
export * from './TokenEntity';
export * from './StabilityProviderEntity';
export * from './BorrowingMarketStateEntity';
export * from './StabilityPoolStateEntity';
export * from './StakingPoolStateEntity';
export * from './MetricsEntity';
export * from './UsdhEntity';
export * from './StrategyEntity';
export * from './ShareMintEntity';
export * from './ShareHolderEntity';
export * from './StrategyStateEntity';
export * from './WhirlpoolEntity';
export * from './WhirlpoolStateEntity';
export * from './DexTypeEntity';
export * from './VaultEntity';
export * from './RewardEntity';
export * from './RewardEarnedEntity';
export * from './PriceEntity';
export * from './TokenHistoryEntity';
export * from './TokenHistorySourceEntity';
export * from './TokenHistoryFieldEntity';
export * from './ProgramAccountEntity';
export * from './TokenMintEntity';
export * from './TradeAggregatorEntity';
export * from './TradeEntity';
export * from './TradeSourceEntity';
export * from './StrategyMetricsEntity';

export const CLUSTER_TABLE: string = 'cluster';
export const COLLATERAL_TABLE: string = 'collateral';
export const DEX_TYPE: string = 'dex_type';
export const LOAN_TABLE: string = 'loan';
export const OWNER_TABLE: string = 'owner';
export const VAULT_TABLE: string = 'vault';
export const TOKEN_TABLE: string = 'token';
export const METRICS_TABLE: string = 'metrics';
export const BORROWING_MARKET_STATE_TABLE: string = 'borrowing_market_state';
export const STABILITY_POOL_STATE_TABLE: string = 'stability_pool_state';
export const STAKING_POOL_STATE_TABLE: string = 'staking_pool_state';
export const STABILITY_PROVIDER_TABLE: string = 'stability_provider';
export const USDH_TABLE: string = 'usdh';
export const LIDO_USDH_DEBT_FUNCTION = 'get_lido_usdh_debt';
export const STRATEGY_TABLE: string = 'strategy';
export const SHARE_MINT_TABLE: string = 'share_mint';
export const STRATEGY_STATE_TABLE: string = 'strategy_state';
export const SHARE_HOLDER_TABLE: string = 'share_holder';
export const WHIRLPOOL_TABLE: string = 'whirlpool';
export const WHIRLPOOL_STATE_TABLE: string = 'whirlpool_state';
export const REWARD_TABLE = 'reward';
export const REWARD_EARNED_TABLE = 'reward_earned';
export const PRICE_TABLE = 'price';
export const TOKEN_HISTORY_TABLE = 'token_history';
export const TOKEN_HISTORY_FIELD_TABLE = 'token_history_field';
export const TOKEN_HISTORY_SOURCE_TABLE = 'token_history_source';
export const TRADE_TABLE = 'trade';
export const TOKEN_MINT_TABLE = 'token_mint';
export const PROGRAM_ACCOUNT_TABLE = 'program_account';
export const TRADE_AGGREGATOR_TABLE = 'trade_aggregator';
export const TRADE_SOURCE_TABLE = 'trade_source';
export const STRATEGY_METRICS_TABLE = 'strategy_metrics';
export const API_SCHEMA: string = 'api';
