export * from './ClusterEntity';
export * from './CollateralEntity';
export * from './LoanEntity';
export * from './OwnerEntity';
export * from './TokenEntity';
export * from './StabilityProviderEntity';
export * from './BorrowingMarketStateEntity';
export * from './StabilityPoolStateEntity';
export * from './StakingPoolStateEntity';
export * from './MetricsEntity';
export * from './UsdhEntity';
export * from './VaultEntity';
export * from './PriceEntity';
export * from './TokenHistoryEntity';
export * from './TokenHistorySourceEntity';
export * from './TokenHistoryFieldEntity';
export * from './ProgramAccountEntity';
export * from './TokenMintEntity';
export * from './MetricsSourceEntity';
export * from './InstructionEntity';
export * from './PriceTypeEntity';
export * from './RawInstructionEntity';
export * from './OwnerScreeningEntity';
export * from './RecentSlotEntity';
export * from './HubbleInstructionEntity';

export const CLUSTER_TABLE: string = 'cluster';
export const COLLATERAL_TABLE: string = 'collateral';
export const LOAN_TABLE: string = 'loan';
export const OWNER_TABLE: string = 'owner';
export const VAULT_TABLE: string = 'vault';
export const TOKEN_TABLE: string = 'token';
export const METRICS_TABLE: string = 'metrics';
export const BORROWING_MARKET_STATE_TABLE: string = 'borrowing_market_state';
export const STABILITY_POOL_STATE_TABLE: string = 'stability_pool_state';
export const STAKING_POOL_STATE_TABLE: string = 'staking_pool_state';
export const STABILITY_PROVIDER_TABLE: string = 'stability_provider';
export const USDH_TABLE: string = 'usdh';
export const LIDO_USDH_DEBT_FUNCTION = 'get_lido_usdh_debt';
export const PRICE_TABLE = 'price';
export const TOKEN_HISTORY_TABLE = 'token_history';
export const TOKEN_HISTORY_FIELD_TABLE = 'token_history_field';
export const TOKEN_HISTORY_SOURCE_TABLE = 'token_history_source';
export const TOKEN_MINT_TABLE = 'token_mint';
export const PROGRAM_ACCOUNT_TABLE = 'program_account';
export const METRICS_SOURCE_TABLE = 'metrics_source';
export const INSTRUCTION_TABLE = 'instruction';
export const PRICE_TYPE_TABLE = 'price_type';
export const RAW_INSTRUCTION_TABLE = 'raw_instruction';
export const OWNER_SCREENING_TABLE = 'owner_screening';
export const RECENT_SLOT_TABLE = 'recent_slot';
export const HUBBLE_INSTRUCTION_TABLE = 'hubble_instruction';

export const API_SCHEMA: string = 'api';
