name: Build NPM packages

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build NPM packages
    needs: prettier
    steps:

      # 1. provide Personal Access Token for checkout@v2
      # GITHUB_TOKEN (personal access token) always exists in repositories, does not have to be explicitly added
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install lerna v4
        run: |
          rm -rf /usr/local/bin/lerna
          npm install -g lerna@4.0.0

      - name: Install dependencies
        run: |
          npm ci
          lerna bootstrap

      - name: Build packages
        run: lerna run build

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run prettier
        run: |-
          npx prettier --check '{**/*,*}.{js,ts,jsx,tsx}'
