name: Build NPM packages

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build NPM packages
    needs: prettier
    steps:

    - name: test
      run: |
        echo $PATH
        lerna -v
        whereis lerna

    # 1. provide Personal Access Token for checkout@v2
    # GITHUB_TOKEN (personal access token) always exists in repositories, does not have to be explicitly added
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        lerna -v
        npm ci
        lerna -v
        lerna bootstrap

    - name: Build packages
      run: lerna run build

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run prettier
        run: |-
          npx prettier --check '{**/*,*}.{js,ts,jsx,tsx}'
